const Message = {
  ALL_FIELDS_REQUIRED: "All fields are required!",
  SUMMARY_NOT_FOUND: "Github summary not found!",
  REPOS_NOT_FOUND: "Github github repos not found!",
  SUMMARY_FETCHED: "Github summary fetched successfully",
  REPOS_FETCHED: "Github repos fetched successfully",
  USERNAME_EMAIL_REQUIRED: "Invalid username or email",
  USER_ALREADY_EXISTS: "User already exists",
  USERNAME_ALREADY_EXISTS: "Username already exists",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_REGISTERED: "User already registered",
  USER_LOGGED_IN: "User logged in",
  USER_CREATED_SUCCESSFULLY: "User created successfully",
  INVALID_PASSWORD: "Invalid password",
  INVALID_TOKEN: "Invalid token",
  USER_LOGGED_OUT: "User logged out",
  UNAUTHORIZED_REQUEST: "User is not authorized",
  REFRESH_TOKEN_EXPIRED: "Refresh token expired",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed",
  SOMETHING_WENT_WRONG_REGISTERING_USER: "Something went wrong while registering the user",
  SOMETHING_WENT_WRONG_REGISTERING_AVATAR: "Something went wrong while uploading avatar to",
  MESSAGE_SEND: "Message send",
  CV_NOT_PROVIDED: "CV not provided by user",
  CV_NOT_FOUND: "CV not found",
  CV_NOT_UPLOADED: "CV not uploaded",
  CV_DOWNLOADED: "CV downloaded",
  CV_UPLOADED: "CV uploaded successfully",
  ERROR_DOWNLOADING_CV: "Error downloading CV",
  SECRET_TOKEN_NOT_PROVIDED: "Secret token not provided"
};

export { Message };
